language: node_js
sudo: true
cache:
  apt: true
  yarn: true
  directories:
  - website/.lanyon
node_js:
- 7
script:
- npm run lint
- npm test
before_cache:
- rm -f ./node_modules/.bin/which
before_deploy: node_modules/.bin/lanyon install
deploy:
  skip_cleanup: true
  provider: script
  script: website/.lanyon/bin/deploy
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
env:
  global:
  - secure: GKYptT34MjkLdmHmq3yT+kM9+WU/E6/9fyV3o2yneAPj2Mr5wKD8f3LWwbU/H/CIEZ5/QLM4j5FcpFy8F44gywfhSn2XBy5cwiA8+MbOsukjQKeR7RzCm92fJAVT0t16li7OpiiojTUyXD69EWIPk8DC63m2jZbgsIU9ot9f1U45StRONvr3Mxy9bSOHaEMEpC87rx4HNpQy3eZs6gKtGcQKkDHhs8stYv5ZCVjdxeDP5nzFrTtQTRgQHh/GoOgbgIErSyLpp5uEv+uK3TUGG6fKUyMP/joLP9Y4t03BwLoCU77WCBxYVYSunMYoDycKv10KRSEobyjLEnTr/Nuzb2kL8xF2KmvJA0EAcE1N/h1xMgYTHk1rVtfG2XnQPoTGD4eANvBDCwSPPwxJP/p6R7jxSAWzj3kI2bqsVXUl6AhdUC3MJfpei/hnBkJUNereCLiBVZmJPpxj/z1teBiNc+sKSpuZ0dNoTvUHweOk6lRQOz1CurhqI4nVfuLnLnKVA9gVe+r3tl7jPYmgwFHLoVAAzRtII+WIvKgV8ah2ooi2qtpGV6o7P/+NpblSMJLbGzWpsXFysiYuPcmvH2tJjik0xz4SjjQbe/C9flZre3GF+FF3ef2mEu5oksCpZO4Y34I0fUkngCWJUhTfDN/vLkID+fnVx6lfUJ3pOPkn/Ak=
  - secure: nnyg1JsVfbIbBdKtRAoFbGyVInBFVWo5vA88qp5kz5asoRfFpKWsvejyXBEJGTyT3PnpAIKbh+D4oa59fJ7WMifKCCNqmTh4G6hY81vC3ydmhTCpnuvE3V38Sr8HnXm7YeXJiYgmYdkXMZe0vKP1dWGZN1AevCfIEW6qdvArFPCszwO9rfoUcPlByAExrIHD6U1dJTdRhDA/TUy+1RjIytIFf9Ads2zo9+lu4UR7Aqk03SDnDdrVUfxdFqOq7NuN9QV4K7KBNlMnP0xA435AUE0sD4b6q+ZNAg+LYKjuxJaXzkRxSZb+cqW2No0XEWaUH/9emy6zzRfl5jVPGbFzrhKIO2Cpn9j7z4Ca4GlM/hU1yPoVXMzeOZkjkPtwUzJWbfwsviyOL1v94n2e1fYlm+R6YGHk6uFEkoNhZF7cqZxYNRTv0woDEPB4NZZDYKT6JUC8ZPIeuPpSpqlllutZmdss26EeP+JNLqA44MMkmGP8C5xosi5Uy8vaHReGmQpMiO2e+NC7edDFSrcdUuQd4MLeHkX8wGfIBehNTZIXlOuzzIwR74Kt1Df1D+mHhs+/Jz6H9467aezCy+PUT/mnn6quOsBLp+CLbjOToEnf3QdkPfdSKoys/v6MHKvbwwAAsKjeKRVo4QmQ15CBLGy1edrwfSzaSUxvJDnyApWXEsg=
  - secure: P+pOSckaL/0NgncH6dVTHBX0NunudrHJ0djluavsvEsagwlWw8CbjXDCEWXuO5JHT3TyAm2v/LTJAwWUUw70tIa8hU2RKSRFwMCZZuximJS9TduZV9it3AsziLOkkLIXKAnVewtuuGIwAgsCYeZQdLCAwF4LrCXVFxCZj3v9dIHYZAcaRmpZZGcWD/ZKm7h8EDeSP3Ol02BZ9Xg3lvK+pWnYI+d4CiiqQe3Xv/nwCOh7gL6MX/qBbX/msVzZu7lree5qmAuezTZL7OJW1J8UqlFKmKJo0E6dpAu0bfad4P8Pdp6OO/JyM2fqJcchAUuX28ntkSSpkyuMFXuS20LcGODCGmhE/pMbRdRYytDhosQcxXrlHd0qus10zUCabc4F7/bXrvKHr7umBgqdi7FyXJ38h+g8Hn8rEFFKCdat297nFVFHIRTEXDpCnNnrvJGE7qOSB7y9DvUr7wQXdTBuybNEBkX4D7XFOwslYvTchvWfOVIFfN6qkmvlRS8dqAh+IxH9W7WSUW+EKoNd1gD1/u8lE/NkyRaPzVfKJAa4H9HTiSLR6GRyz572HFhASqxuXkLxs4eVMuzEMudWUNk2qY4Xwm0ZIfUNl1kdDveO93UIDAvtM0I+t+EmWjmUL7x9JocomE7nig7a7qQcOGQ5PX9oMSNQPqbsUBfBUz0VKJY=
