language: node_js
sudo: true
cache:
  apt: true
  directories:
  - node_modules
node_js:
- 4.2.2
# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - g++-4.8
# env:
#   global:
#   - CXX=g++-4.8
script:
- npm run lint
- npm test
